[book]
title = "Amplirust"
description = "A high-performance in-silico PCR tool"
authors = ["Erdi Kilic"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
site-url = "/amplirust/"
git-repository-url = "https://github.com/erdikilic/amplirust"
edit-url-template = "https://github.com/erdikilic/amplirust/edit/main/docs/{path}"
