name: Build & Release

on:
  push:
    tags:
      - "*.*.*" # Trigger on SemVer-like tags such as 0.1.0
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: ""
  PROJECT_NAME: amplirust

# WRITING PERMISSION IS REQUIRED FOR RELEASES
permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ""
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            suffix: ""
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            suffix: ""
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-musl
            suffix: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: ".exe"
          - os: macos-15-intel
            target: x86_64-apple-darwin
            suffix: ""
          - os: macos-latest
            target: aarch64-apple-darwin
            suffix: ""

    steps:
    - uses: actions/checkout@v4

    - name: Install musl toolchain
      if: endsWith(matrix.target, '-musl')
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools cmake
        echo "CC=musl-gcc" >> "$GITHUB_ENV"
        echo "CXX=g++" >> "$GITHUB_ENV"

    - name: Add Rust target
      run: rustup target add ${{ matrix.target }}

    - name: Get version
      id: version
      shell: bash
      run: |
        VERSION="${GITHUB_REF_NAME}"
        echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

    - name: Build
      run: cargo build --release --target ${{ matrix.target }} --verbose

    - name: Run tests
      run: cargo test --release --target ${{ matrix.target }} --verbose

    - name: Rename Binary
      shell: bash
      run: |
        mv target/${{ matrix.target }}/release/${{ env.PROJECT_NAME }}${{ matrix.suffix }} target/${{ matrix.target }}/release/${{ env.PROJECT_NAME }}-${{ steps.version.outputs.version }}-${{ matrix.target }}${{ matrix.suffix }}

    # 1. Upload as Artifact (Optional, useful for debugging build failures)
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}-${{ steps.version.outputs.version }}-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/${{ env.PROJECT_NAME }}-${{ steps.version.outputs.version }}-${{ matrix.target }}${{ matrix.suffix }}

    # 2. Upload to Release (Only runs on tags)
    - name: Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'release'
      with:
        files: target/${{ matrix.target }}/release/${{ env.PROJECT_NAME }}-${{ steps.version.outputs.version }}-${{ matrix.target }}${{ matrix.suffix }}
